### ISSUE TITLE
Window title font size parameterization request

### ISSUE THREAD

**Issue by AlexJakeGreen** [soreau/pixdecor#13]
I observe window title is written with a very tiny font. An attempt to increase _org.gnome.desktop.interface/font-name_ leads to unproportional font rendered in other places.

I think it will be nice to expose the font size parameter in wcm.

https://github.com/soreau/pixdecor/blob/master/src/deco-theme.cpp#L206

**Comment by soreau** [comment]
I think [this function](https://github.com/soreau/pixdecor/blob/master/src/deco-theme.cpp#L103) might need adjusting.

**Comment by soreau** [comment]
@AlexJakeGreen Can you possibly test #27 and see if this fixes the issue here?

**Comment by soreau** [comment]
Closing this since #27 has been merged.
