### ISSUE TITLE
[Bug] pixdecor effects no longer function when a output is changed or removed and regained

### ISSUE THREAD

**Issue by kernaltrap8** [soreau/pixdecor#18]
This has been a issue I have had since I started using pixdecor a couple months ago. Here's a summary of what happens:
- User removes a video output
- User regains output
- `pixdecor` effects no longer animate properly

Here's a ![video](https://github.com/user-attachments/assets/41f5aec3-2e16-401f-9cf3-e7820489e9c0) of the behavior. This happens right after output is lost and regained. A restart of Wayfire mitigates this issue.

**Comment by soreau** [comment]
Does [this patch](https://termbin.com/9pjg) help?

**Comment by soreau** [comment]
Fixed in [this commit](https://github.com/soreau/pixdecor/commit/53465221c2180967898073c3b134f377223d9f06).
