### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by vollowx** [soreau/pixdecor#9]
```
Run-time dependency wayfire found: NO (tried cmake)

meson.build:18:10: ERROR: Dependency lookup for wayfire with method 'pkgconfig' failed: Could not generate cflags for wayfire:
Package glm was not found in the pkg-config search path.
Perhaps you should add the directory containing `glm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glm', required by 'wf-config', not found
```

This turns up when I was running `meson setup build --prefix=/usr`, I've installed `glm` and `wayfire` packages (tried both AUR and chaotic-aur).

**Comment by soreau** [comment]
I think the basic problem is that, due to a change in glm, you should install cmake and then reinstall wayfire and pixdecor.

**Comment by vollowx** [comment]
I'm still unable to build this, but anyway thx for ur efforts!

**Comment by soreau** [comment]
Thank you for following up. Do you still get the same error even after installing cmake before rebuilding wayfire and wf-config? If you can post the complete output starting with the command you're running to build, we might be able to spot the problem.

**Comment by vollowx** [comment]
Actually I can't build wayfire manually, either. The built wayfire binary can't find wf-config

**Comment by soreau** [comment]
I see. It might be that you need to set LD_LIBRARY_PATH to the directory containing libwf-config.so. In any event, if you would like to try to fix it, we can keep communicating here, on IRC/Matrix/Discord or you can create a discussion on github.com/wayfirewm/wayfire.

**Comment by vollowx** [comment]
Thanks for your advice, however I am currently busy and can just accept building from AUR.

I'll try to figure out the problem as soon as I have some free time.
